packages:
  - "client"
  - "database"
  - "@party-box/common"
  - "@party-box/prisma"
  - "api/*"
  - "scripts"

  # This one is just for Docker image builds. We use a temp directory named 'function'
  - "function"
