packages:
  - "client"
  - "database"
  - "@party-box/*"
  - "api/*"
  - "config"
  - "packages/*"

  # This one is just for Docker image builds. We use a temp directory named 'function'
  - "function"
