# fly.toml app configuration file generated for partybox-search on 2023-08-05T12:48:49-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "partybox-search"
primary_region = "yyz"

[build]
image = "getmeili/meilisearch"

[mounts]
source = "search_data"
destination = "/meili_data"

[[services]]
http_checks = []
internal_port = 7700
processes = ["app"]
protocol = "tcp"
script_checks = []
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
