name: apply-migrations

on:
  push:
    branches:
      - main
    paths:
      - "src/db/migrations/**"
      - ".github/workflows/apply-migrations.yml"

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.3.1

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.6.11
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run migrations
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          DATABASE_AUTH_TOKEN: ${{secrets.DATABASE_AUTH_TOKEN}}
        run: pnpm migrate
