name: CD/party-box-deleteEvent

on:
  push:
    branches:
      - dev
    paths:
      - "api/party-box-deleteEvent/**"
      - ".github/workflows/cd-party-box-deleteEvent.yml"
      - ".github/workflows/cd-lambda-default.yml"

jobs:
  deploy:
    name: Deploy Lambda
    uses: ./.github/workflows/cd-lambda-default.yml
    with:
      function-name: party-box-deleteEvent
    secrets: inherit
