name: CD/party-box-handleTicketPurchase

on:
  push:
    branches:
      - dev
    paths:
      - "api/party-box-handleTicketPurchase/**"
      - ".github/workflows/cd-party-box-handleTicketPurchase.yml"
      - ".github/workflows/cd-lambda-default.yml"

jobs:
  deploy:
    name: Deploy Lambda
    uses: ./.github/workflows/cd-lambda-default.yml
    with:
      function-name: party-box-handleTicketPurchase
    secrets: inherit
