name: CD/party-box-sendEventNotifications

on:
  push:
    branches:
      - dev
    paths:
      - "api/party-box-sendEventNotifications/**"
      - ".github/workflows/cd-party-box-sendEventNotifications.yml"
      - ".github/workflows/cd-lambda-default.yml"

jobs:
  deploy:
    name: Deploy Lambda
    uses: ./.github/workflows/cd-lambda-default.yml
    with:
      function-name: party-box-sendEventNotifications
    secrets: inherit
