name: Dev/DB/Migrate

on:
  push:
    branches:
      - dev
    paths:
      - "database/**"
      - ".github/workflows/dev-migrate-db.yml"

jobs:
  migrate-db:
      name: Perform Prisma migration
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - uses: pnpm/action-setup@v2.2.2
          with:
            run_install: true

        - name: Migrate
          working-directory: database
          env:
            DATABASE_URL: ${{ secrets.DEV_POSTGRES_URL }}
          run: |
            pnpm -F database migrate:dev -n "${{ github.event.head_commit.message }}"