name: Prod/DB/Migrate

on:
  push:
    branches:
      - main
    paths:
      - "database/**"
      - ".github/workflows/prod-migrate-db.yml"

jobs:
  migrate-db:
      name: Perform Prisma migration
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - uses: actions/setup-node@v3.4.1
          with:
            node-version: 16

        - name: Migrate
          working-directory: database
          env:
            DATABASE_URL: ${{ secrets.DEV_POSTGRES_URL }}
          run: |
            yarn install
            yarn workspace database migrate:prod