name: Prod/DB/Migrate

on:
  push:
    branches:
      - main
    paths:
      - "database/**"
      - ".github/workflows/prod-migrate-db.yml"

jobs:
  migrate-db:
    name: Perform Prisma migration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: |
            - args: [-P]

      - name: Migrate
        working-directory: database
        env:
          DATABASE_URL: ${{ secrets.PROD_POSTGRES_URL }}
        run: |
          pnpm install
          pnpm -F @party-box/prisma migrate:prod
